language: objective-c
osx_image: xcode8.2
xcode_workspace: TicTacToe.xcworkspace
xcode_scheme: TicTacToeCommandLine

script: xcodebuild test -workspace TicTacToe.xcworkspace -scheme TicTacToeiOS -sdk iphoneos10.2
